In [8]:
import pandas as pd

In [28]:
import numpy as np

In [9]:
pd.__version__

'2.3.3'

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [47]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [48]:
df.fuel_type.nunique()

3

In [53]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [58]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [57]:
df.horsepower.median()

np.float64(254.0)

In [61]:
df.horsepower.mode()[0]

np.float64(252.0)

In [71]:
df1 = df.horsepower.fillna(252.0)

In [73]:
df1

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...  
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [74]:
df1.median()

np.float64(252.0)

In [77]:
df.horsepower.median() > df1.median()

np.True_

In [26]:
x = df[df['origin'] == 'Asia'][['vehicle_weight','model_year']][:7].values

In [27]:
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [43]:
x.shape

(7, 2)

In [29]:
xt = x.T

In [30]:
xt

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [41]:
xt.shape

(2, 7)

In [39]:
xtx = x.dot(xt)

In [40]:
xtx

array([[21961616, 22250432, 21921212, 22688888, 20753972, 24173916,
        22897924],
       [22250432, 22544164, 22209324, 22990376, 21022444, 24498332,
        23201348],
       [21921212, 22209324, 21880909, 22646666, 20716479, 24128437,
        22855443],
       [22688888, 22990376, 22646666, 23448884, 21428846, 24992538,
        23662582],
       [20753972, 21022444, 20716479, 21428846, 19630549, 22818647,
        21629633],
       [24173916, 24498332, 24128437, 24992538, 22818647, 26646941,
        25217899],
       [22897924, 23201348, 22855443, 23662582, 21629633, 25217899,
        23878861]])

In [44]:
xtx_inv = np.linalg.pinv(xtx)

In [45]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [53]:
y.shape

(7,)

In [48]:
r = xt.dot(xtx_inv)

In [49]:
r

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [54]:
w = r.dot(y)

In [55]:
w.sum()

np.float64(0.3691969690492492)